# Generated by Django 3.2 on 2025-11-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BangJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.BigIntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BiharJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.BigIntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Punejob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.BigIntegerField(max_length=20)),
            ],
        ),
    ]
